### ISSUE TITLE
Error:  uninitialized constant Aliyun (NameError)

### ISSUE THREAD

**Issue by khoada** [VICTOR-LUO-F/aliyun-sms#1]
Hi there,
I used your gem to send Aliyun SMS. But after add gem and config step "在 rails 应用目录 config/initializers/ 下创建脚本文件 aliyun-sms.rb，在文件中加入以下内容"
=> I got error when try run rails console
config/initializers/aliyun_sms.rb:1:in `<top (required)>': uninitialized constant Aliyun (NameError)

Please you help me to resolve it. 
Thanks you

**Comment by VICTOR-LUO-F** [comment]
I also meet this problem, the reason perhaps is the Ruby-Gems resource error.
I resolve this problem by changing the install resource to Github. 
For example,  you can add code following in  ./Gemfile
`gem 'aliyun-sms', git: 'https://github.com/VICTOR-LUO-F/aliyun-sms.git'`

**Comment by khoada** [comment]
> gem  'aliyun-sms', git: 'https://github.com/VICTOR-LUO-F/aliyun-sms.git'

After i added it to Gemfile, it runs well

Thank you so much

**Comment by VICTOR-LUO-F** [comment]
:)
