### ISSUE TITLE
2018-5-28 依然可用。特此感谢~~

### ISSUE THREAD

**Issue by 1c7** [VICTOR-LUO-F/aliyun-sms#11]
### 感谢你写这个 gem
节省了我不少时间，不用自己写

(此 issue 可随时关闭)

**Comment by 1c7** [comment]
![41414](https://user-images.githubusercontent.com/1804755/40599215-ac1eeb74-627e-11e8-8a23-f0a5b03ad7cd.jpg)

**Comment by 1c7** [comment]
![screenshot_20180528-134043](https://user-images.githubusercontent.com/1804755/40599231-c1ff907e-627e-11e8-8698-c1828be627ea.jpg)

**Comment by victor-luo-f** [comment]
谢谢支持！

**Comment by 1c7** [comment]
补充：2020-2-26 了，另外的项目又需要阿里云短信发送。
此 gem 依然可用。
