### ISSUE TITLE
参数名称的问题

### ISSUE THREAD

**Issue by shaojunda** [VICTOR-LUO-F/aliyun-sms#4]
![image](https://user-images.githubusercontent.com/5165454/28658468-12988536-72de-11e7-930b-d442ef80b487.png)
电话号码的键值是「PhoneNumbers」吧？

**Comment by VICTOR-LUO-F** [comment]
您好，调用 gem 的键值是 phone_number。 这个 gem 在发送加密的信息，组织字符串的时侯，会转换成阿里云规定的 表示方式。

**Comment by shaojunda** [comment]
请问在哪里转换的呢？我在代码中没有找到哦
