### ISSUE TITLE
https://rubygems.org/downloads/aliyun-sms-0.1.0.gem这个版本解压后发现data.tar.gz内容为空？

### ISSUE THREAD

**Issue by blogbin** [VICTOR-LUO-F/aliyun-sms#6]
https://rubygems.org/downloads/aliyun-sms-0.1.0.gem这个版本解压后发现data.tar.gz内容为空，能否重新在rubygems.org上传一个新版本？

**Comment by VICTOR-LUO-F** [comment]
可能由于网络原因，当时提交出了问题。我现在正在根据新的接口开发新版本，到时候一并改正。
